version: "3"

services:
  node:
    image: node:16
    container_name: trybesmith
    tty: true
    stdin_open: true
    env_file: ./.env
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db

  db:
    container_name: trybesmith_db
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

networks:
  default:
    name: trybesmith_net
